import assert from 'node:assert/strict'
import { chromium } from 'playwright'

const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1366, height: 900 } })

await page.goto('http://127.0.0.1:5173/', { waitUntil: 'commit', timeout: 10000 })
await page.getByRole('button', { name: 'Dashboard' }).waitFor({ timeout: 20000 })
const text = async () => ((await page.textContent('body')) ?? '').replace(/\s+/g, ' ')
assert((await text()).includes('Ice Cream Booth Tycoon'), 'Dashboard should feel like the tycoon home screen')
assert((await text()).includes("Today's Score"), 'Dashboard should show today score')
assert((await text()).includes('Current Streak'), 'Dashboard should show current streak')
assert((await text()).includes('Best Seller Today'), 'Dashboard should show best seller today')
assert((await text()).includes('Recent Achievements'), 'Dashboard should show recent achievements')
const dashboardImages = await page
  .locator('img')
  .evaluateAll((images) => images.map((image) => (image as HTMLImageElement).getAttribute('src') ?? ''))
assert(dashboardImages.some((src) => src.includes('/images/homepage-hero.png')), 'Dashboard should load homepage hero image')
assert(dashboardImages.some((src) => src.includes('/images/booth-scene.png')), 'Dashboard should load booth scene image')
assert(dashboardImages.some((src) => src.includes('/images/couple-badge.png')), 'Dashboard should load couple badge image')
assert(dashboardImages.some((src) => src.includes('/images/couple-closeup.png')), 'Dashboard should load helper mascot image')
await page.locator('.nav-tabs').getByRole('button', { name: 'Achievements', exact: true }).click()
assert((await text()).includes('Achievement Wall'), 'Achievements page should show the full badge wall')
assert((await text()).includes('Unlocked 23/05/2026'), 'Achievements should display unlock dates')
await page.locator('.nav-tabs').getByRole('button', { name: 'Dashboard' }).click()
await page.getByRole('button', { name: 'Daily Report', exact: true }).click()
await page.locator('input[type="date"]').fill('2026-05-23')

await page.getByText('Total revenue').waitFor()
assert((await text()).includes('4.060,00 kr.'), 'Seeded 23/05/2026 revenue should show 4.060,00 kr.')
assert((await text()).includes('812,00 kr.'), 'Seeded 23/05/2026 sales VAT should show 812,00 kr.')

const drysRow = page.locator('tr').filter({ hasText: 'Drys' })
await drysRow.locator('input[type="number"]').first().fill('4')
assert((await text()).includes('4.067,00 kr.'), 'Changing Drys quantity should update total revenue')
await page.getByRole('button', { name: 'Save report' }).click()
assert((await text()).includes('Day Complete'), 'Saving a daily report should show the end-of-day result screen')
assert((await text()).includes('XP earned today'), 'Day Complete should show XP earned today')
assert((await text()).includes('Worst Seller'), 'Day Complete should show the worst-selling product')
assert((await text()).includes('Level progress'), 'Day Complete should show level progress')
await page.getByRole('button', { name: 'Continue' }).click()

await page.getByRole('button', { name: 'Expenses', exact: true }).click()
await page.getByRole('button', { name: 'Cash register' }).click()
await page.getByLabel('Quick expense amount in DKK').fill('399')
await page.getByRole('button', { name: 'Save expense' }).click()
assert((await text()).includes('Cash register system'), 'Expenses should support cash register system entries')
assert((await text()).includes('399,00 kr.'), 'Expense amounts should show as DKK')

await page.getByRole('button', { name: 'Stock', exact: true }).click()
assert((await page.textContent('body'))?.includes('Order soon'), 'Low stock should show Order soon')
assert((await page.textContent('body'))?.includes('Storage Shelves'), 'Stock should show the storage shelf screen')
assert((await page.textContent('body'))?.includes('Restock Mission'), 'Stock should show a restock mission panel')
await page.getByRole('button', { name: 'Urgent Refill' }).click()
assert((await page.textContent('body'))?.includes('Out of Stock'), 'Urgent stock filter should show out-of-stock shelves')
await page.getByRole('button', { name: '+1' }).first().click()
assert((await page.textContent('body'))?.includes('Shelf restocked'), 'Quick refill should update a shelf with feedback')
await page.getByRole('button', { name: 'Undo', exact: true }).click()
assert((await page.textContent('body'))?.includes('Undid movement'), 'Accidental stock refill should be undoable')
await page.getByRole('button', { name: 'Add ice cream tub' }).click()
const stockNames = await page
  .locator('tbody tr')
  .evaluateAll((rows) => rows.map((row) => (row.querySelector('td:nth-child(2) input') as HTMLInputElement | null)?.value).filter(Boolean))
assert(stockNames.includes('Vanilje ice cream tub'), 'Stock should allow adding ice cream tub variations')
page.once('dialog', async (dialog) => {
  assert(dialog.message().includes('Vanilje ice cream tub'), 'Stock removal confirmation should name the item')
  await dialog.accept()
})
await page.locator('.stock-table-wrap').getByRole('button', { name: 'Remove' }).first().click()
assert(!(await page.textContent('body'))?.includes('Vanilje ice cream tub'), 'Stock rows should be removable')

await page.getByRole('button', { name: 'Reports', exact: true }).click()
assert((await text()).includes('Monthly Score'), 'Reports should show a monthly scorecard')
assert((await text()).includes('Revenue Graph'), 'Reports should show a revenue graph')
assert((await text()).includes('Profit Champion'), 'Reports should show a profit champion highlight')
assert((await text()).includes('Business health'), 'Reports should show business health')
assert((await text()).includes('Serious Review Tables'), 'Reports should keep review tables available')

await page.getByRole('button', { name: 'Export', exact: true }).click()
const csvDownload = page.waitForEvent('download')
await page.getByRole('button', { name: 'Daily reports CSV' }).click()
assert((await csvDownload).suggestedFilename().endsWith('.csv'), 'Daily report CSV should download')

const xlsxDownload = page.waitForEvent('download')
await page.getByRole('button', { name: 'Workbook XLSX' }).click()
assert((await xlsxDownload).suggestedFilename().endsWith('.xlsx'), 'Workbook XLSX should download')

await browser.close()
console.log('UI smoke checks passed')
