import type { AppData, ExpenseType, PaymentMethod, Product } from './types'

export const expenseTypes: ExpenseType[] = [
  'Ice cream purchase',
  'Waffles/cones',
  'Toppings/guf',
  'Staff wages',
  'Electricity',
  'Packaging',
  'Cleaning',
  'Rent',
  'Cash register system',
  'Card fees',
  'Other',
]

export const paymentMethods: PaymentMethod[] = ['Cash', 'Card', 'MobilePay', 'Bank', 'Other']

export const seedProducts: Product[] = [
  {
    id: 'alm-softice',
    name: 'Alm. Softice',
    category: 'Softice',
    portionSize: '1 portion',
    costPerUnit: 0,
    sellingPrice: 45,
    notes: '',
  },
  {
    id: 'lille-softice',
    name: 'Lille Softice',
    category: 'Softice',
    portionSize: '1 small portion',
    costPerUnit: 0,
    sellingPrice: 35,
    notes: '',
  },
  {
    id: '1-kugle',
    name: '1 Kugle',
    category: 'Kugleis',
    portionSize: '1 scoop',
    costPerUnit: 0,
    sellingPrice: 37,
    notes: '',
  },
  {
    id: '2-kugler',
    name: '2 Kugler',
    category: 'Kugleis',
    portionSize: '2 scoops',
    costPerUnit: 0,
    sellingPrice: 50,
    notes: '',
  },
  {
    id: '3-kugler',
    name: '3 Kugler',
    category: 'Kugleis',
    portionSize: '3 scoops',
    costPerUnit: 0,
    sellingPrice: 63,
    notes: '',
  },
  {
    id: 'drys',
    name: 'Drys',
    category: 'Topping',
    portionSize: '1 topping',
    costPerUnit: 0,
    sellingPrice: 7,
    notes: '',
  },
  {
    id: 'flodeskum',
    name: 'Flødeskum',
    category: 'Topping',
    portionSize: '1 topping',
    costPerUnit: 0,
    sellingPrice: 7,
    notes: '',
  },
  {
    id: 'syltetoj',
    name: 'Syltetøj',
    category: 'Topping',
    portionSize: '1 topping',
    costPerUnit: 0,
    sellingPrice: 7,
    notes: '',
  },
  {
    id: 'softice-topping',
    name: 'Softice Topping',
    category: 'Topping',
    portionSize: '1 topping',
    costPerUnit: 0,
    sellingPrice: 15,
    notes: '',
  },
  {
    id: 'guf',
    name: 'Guf',
    category: 'Add-on',
    portionSize: '1 portion',
    costPerUnit: 0,
    sellingPrice: 7,
    notes: 'Calculated from guf bucket settings unless manually overridden.',
    costSource: 'gufSetting',
  },
  {
    id: 'flodebolle',
    name: 'Flødebolle',
    category: 'Add-on',
    portionSize: '1 piece',
    costPerUnit: 0,
    sellingPrice: 7,
    notes: 'Imported from POS year-to-date sales.',
  },
]

export const seedData: AppData = {
  products: seedProducts,
  dailyReports: [
    {
      id: 'report-2026-05-23',
      date: '2026-05-23',
      items: [
        { productId: 'drys', quantity: 3 },
        { productId: '1-kugle', quantity: 48 },
        { productId: '2-kugler', quantity: 44 },
        { productId: '3-kugler', quantity: 1 },
      ],
      notes: 'Example report from 23/05/2026.',
    },
    {
      id: 'report-2026-05-24',
      date: '2026-05-24',
      items: [
        { productId: 'drys', quantity: 23 },
        { productId: '1-kugle', quantity: 42 },
        { productId: '2-kugler', quantity: 48 },
        { productId: 'guf', quantity: 20 },
      ],
      notes: 'Imported from sales register for 24/05/2026.',
    },
    {
      id: 'report-2026-05-25',
      date: '2026-05-25',
      items: [
        { productId: '1-kugle', quantity: 4 },
        { productId: '2-kugler', quantity: 8 },
        { productId: 'guf', quantity: 4 },
      ],
      notes: 'Imported from sales register for 25/05/2026.',
    },
    {
      id: 'report-2026-ytd-adjustment',
      date: '2026-07-29',
      items: [
        { productId: 'lille-softice', quantity: 279 },
        { productId: 'alm-softice', quantity: 165 },
        { productId: 'drys', quantity: 454 },
        { productId: '1-kugle', quantity: 663 },
        { productId: '2-kugler', quantity: 637 },
        { productId: '3-kugler', quantity: 46 },
        { productId: 'flodebolle', quantity: 2 },
        { productId: 'syltetoj', quantity: 45 },
        { productId: 'flodeskum', quantity: 63 },
        { productId: 'softice-topping', quantity: 100 },
        { productId: 'guf', quantity: 422 },
      ],
      notes: 'Year-to-date POS adjustment through 29/07/2026. This fills the difference between saved daily reports and POS totals: 3.121 items and 93.762 kr. revenue.',
    },
  ],
  expenses: [
    {
      id: 'expense-first-product-purchase-2026-06-28',
      date: '2026-06-28',
      type: 'Ice cream purchase',
      description: 'First product purchase',
      amount: 9370.36,
      paymentMethod: 'Bank',
      notes: 'Invoice total shown as 7.496,29 kr. excl. moms: 6.541,44 kr. product net plus 954,85 kr. afgift. Entered as 9.370,36 kr. incl. moms so net expense matches the invoice total.',
    },
    {
      id: 'expense-more-purchases-ice-cream-2026-06-28',
      date: '2026-06-28',
      type: 'Ice cream purchase',
      description: "Carte d'Or pistacie 5000ml",
      amount: 678,
      paymentMethod: 'Bank',
      notes: 'Additional purchase from receipt: 2 x 339,00 kr. incl. moms.',
    },
    {
      id: 'expense-more-purchases-waffles-2026-06-28',
      date: '2026-06-28',
      type: 'Waffles/cones',
      description: 'IDUN waffles/cones',
      amount: 643,
      paymentMethod: 'Bank',
      notes: 'Additional purchase from receipt: Vaffel 3 kugler 240 stk, 280,00 kr.; Vaffel 2 kugler 390 stk, 363,00 kr. incl. moms.',
    },
    {
      id: 'expense-more-purchases-flodeskum-2026-06-28',
      date: '2026-06-28',
      type: 'Toppings/guf',
      description: 'Debic flødeskum spray',
      amount: 125.9,
      paymentMethod: 'Bank',
      notes: 'Additional purchase from receipt: 2 x Flødeskum spray sødet 35% 700ml at 62,95 kr. incl. moms.',
    },
    {
      id: 'expense-softice-mix-purchase-2026-07-14',
      date: '2026-07-14',
      type: 'Ice cream purchase',
      description: 'Softice Mix 5L',
      amount: 2829.91,
      paymentMethod: 'Bank',
      notes: 'Invoice total shown as 2.263,93 kr. excl. moms for 8 kolli Softice Mix 5L. Entered as 2.829,91 kr. incl. moms.',
    },
    {
      id: 'expense-ice-cream-restock-2026-07-14',
      date: '2026-07-14',
      type: 'Ice cream purchase',
      description: 'Ice cream restock',
      amount: 14733.66,
      paymentMethod: 'Bank',
      notes: 'Invoice total shown as 11.786,93 kr. excl. moms for 41 kolli assorted ice cream and softice mix. Entered as 14.733,66 kr. incl. moms.',
    },
    {
      id: 'expense-unilever-restock-2026-07-17',
      date: '2026-07-17',
      type: 'Ice cream purchase',
      description: 'Unilever restock',
      amount: 17681.6,
      paymentMethod: 'Bank',
      notes: 'Invoice 6356784764. Total shown as 14.145,28 kr. excl. moms for 45 kolli assorted ice cream and softice mix. Entered as 17.681,60 kr. incl. moms.',
    },
    {
      id: 'expense-paycheck-2026-07-29',
      date: '2026-07-29',
      type: 'Staff wages',
      description: 'Paycheck withdrawal',
      amount: 5000,
      paymentMethod: 'Bank',
      notes: 'Paycheck taken out of the business. Staff wages are treated as no-moms expenses, so the full 5.000 kr. reduces profit.',
    },
    {
      id: 'expense-unilever-restock-2026-08-12',
      date: '2026-08-12',
      type: 'Ice cream purchase',
      description: 'Unilever restock',
      amount: 17012.2,
      paymentMethod: 'Bank',
      notes: 'Invoice screenshot received 12/08/2026. Total shown as 13.609,76 kr. excl. moms for 42 kolli assorted ice cream and softice mix. Entered as 17.012,20 kr. incl. moms.',
    },
  ],
  recurringExpenses: [
    {
      id: 'recurring-cash-register',
      type: 'Cash register system',
      description: 'Cash register system',
      amount: 0,
      paymentMethod: 'Card',
      dayOfMonth: 1,
      notes: 'Monthly payment. Enter the amount when you know it.',
      active: true,
    },
  ],
  stockItems: [
    {
      id: 'stock-guf',
      name: 'Guf portions',
      unit: 'portions',
      startingStock: 40,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 20,
      costPerUnit: 8,
      linkedProductId: 'guf',
      notes: 'Usage follows Guf sales.',
    },
    {
      id: 'stock-drys',
      name: 'Drys topping portions',
      unit: 'portions',
      startingStock: 5,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 10,
      costPerUnit: 0,
      linkedProductId: 'drys',
      notes: 'Seeded low to demonstrate reorder alerts.',
    },
    {
      id: 'stock-kugleis',
      name: 'Kugleis tubs',
      unit: 'tubs',
      startingStock: 7,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 3,
      costPerUnit: 0,
      notes: 'Manual tracking first because scoop yield depends on tub size.',
    },
    {
      id: 'stock-cdo-chocolate-5l',
      name: "Carte d'Or Chocolate 5L",
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 255.97,
      notes: 'First product purchase line 33428. 3 kolli, line cost 767,90 kr. excl. moms.',
    },
    {
      id: 'stock-cdo-vanilla-5l',
      name: "Carte d'Or Vanilla 5L",
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 255.97,
      notes: 'Ice cream restock line 47414. 5 kolli, line cost 1.279,83 kr. excl. moms.',
    },
    {
      id: 'stock-cdo-jordbaer-5l',
      name: "Carte d'Or Jordbær 5L",
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 255.97,
      notes: 'First product purchase line 80656. 3 kolli, line cost 767,90 kr. excl. moms.',
    },
    {
      id: 'stock-cdo-lakrids-5l',
      name: "Carte d'Or Lakrids 5L",
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 277.09,
      notes: 'First product purchase line 00414. 3 kolli, line cost 831,27 kr. excl. moms.',
    },
    {
      id: 'stock-cdo-saltet-karamel-5l',
      name: "Carte d'Or Saltet Karamel 5L",
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 277.09,
      notes: 'First product purchase line 46763. 3 kolli, line cost 831,27 kr. excl. moms.',
    },
    {
      id: 'stock-frisko-regnbue-tutti-frutti-5l',
      name: 'Frisko Regnbue/Tutti Frutti 5L',
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 277.09,
      notes: 'First product purchase line 81557. 3 kolli, line cost 831,27 kr. excl. moms.',
    },
    {
      id: 'stock-frisko-choco-cookie-5l',
      name: 'Frisko Choco Cookie 5000ml',
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 288.63,
      notes: 'Ice cream restock line 82333. 3 kolli, line cost 865,88 kr. excl. moms.',
    },
    {
      id: 'stock-cdo-hindbaersorbet-2-4l-x2',
      name: "Carte d'Or Vegansk Hindbærsorbet 2,4L x2",
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 314.62,
      notes: 'First product purchase line 59641. 3 kolli, line cost 943,87 kr. excl. moms.',
    },
    {
      id: 'stock-cdo-mangosorbet-2-4l-x2',
      name: "Carte d'Or Vegan Mangosorbet 2,4L x2",
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 314.62,
      notes: 'First product purchase line 59632. 3 kolli, line cost 943,87 kr. excl. moms.',
    },
    {
      id: 'stock-cdo-mint-chokolade-5-5l',
      name: "Carte d'Or Mint/Chokolade 5,5L",
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 337.65,
      notes: 'First product purchase line 83358. 3 kolli, line cost 1.012,96 kr. excl. moms.',
    },
    {
      id: 'stock-softice-mix-5l',
      name: 'Softice Mix 5L',
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 282.99,
      notes: 'First product purchase line 40723. 2 kolli, line cost 565,98 kr. excl. moms.',
    },
    {
      id: 'stock-cdo-pistacie-5l',
      name: "Carte d'Or Pistacie 5000ml",
      unit: 'stk',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 339,
      notes: 'Additional purchase receipt. 2 stk, line cost 678,00 kr. incl. moms.',
    },
    {
      id: 'stock-frisko-pistacie-5l',
      name: 'Frisko Pistacie 5000ml',
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 277.09,
      notes: 'Unilever invoice 6356784764. 5 kolli, line cost 1.385,45 kr. excl. moms.',
    },
    {
      id: 'stock-cdo-pistacie-5-5l',
      name: "Carte d'Or Pistacie 5,5L",
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 337.65,
      notes: 'Ice cream restock line 82119. 3 kolli, line cost 1.012,96 kr. excl. moms.',
    },
    {
      id: 'stock-idun-vaffel-3-kugler-240stk',
      name: 'IDUN Vaffel 3 kugler 71x168mm 240stk',
      unit: 'krt',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 280,
      notes: 'Additional purchase receipt. 1 krt, line cost 280,00 kr. incl. moms.',
    },
    {
      id: 'stock-idun-vaffel-2-kugler-390stk',
      name: 'IDUN Vaffel 2 kugler 60x153mm 390stk',
      unit: 'krt',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 363,
      notes: 'Additional purchase receipt. 1 krt, line cost 363,00 kr. incl. moms.',
    },
    {
      id: 'stock-debic-flodeskum-spray-700ml',
      name: 'Debic Flødeskum spray sødet 35% 700ml',
      unit: 'stk',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 62.95,
      notes: 'Additional purchase receipt. 2 stk, line cost 125,90 kr. incl. moms.',
    },
    {
      id: 'stock-bj-cookie-dough-4-5l-x2',
      name: 'B&J Cookie Dough 4,5L x2',
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 804.32,
      notes: 'Unilever invoice 6356784764. 3 kolli, line cost 2.412,96 kr. excl. moms.',
    },
    {
      id: 'stock-cdo-banana-chocolate-5-5l',
      name: 'CDO Banana & Chocolate 5,5L',
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 337.65,
      notes: 'Unilever restock received 12/08/2026. 1 kolli, line cost 337,65 kr. excl. moms.',
    },
    {
      id: 'stock-cdo-raspberry-white-chocolate-5-5l',
      name: 'CDO Raspberry & White Chocolate 5,5L',
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 337.65,
      notes: 'Unilever restock received 12/08/2026. 1 kolli, line cost 337,65 kr. excl. moms.',
    },
    {
      id: 'stock-carte-dor-choc-hazelnut-5-5l',
      name: "Carte d'Or Choc Hazelnut 5,5L",
      unit: 'kolli',
      startingStock: 0,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 1,
      costPerUnit: 337.65,
      notes: 'Unilever restock received 12/08/2026. 1 kolli, line cost 337,65 kr. excl. moms.',
    },
  ],
  stockMovements: [
    { id: 'movement-first-purchase-cdo-chocolate-5l', stockItemId: 'stock-cdo-chocolate-5l', date: '2026-06-28', type: 'Received', quantity: 3, notes: 'First product purchase. Line cost 767,90 kr. excl. moms.' },
    { id: 'movement-first-purchase-cdo-jordbaer-5l', stockItemId: 'stock-cdo-jordbaer-5l', date: '2026-06-28', type: 'Received', quantity: 3, notes: 'First product purchase. Line cost 767,90 kr. excl. moms.' },
    { id: 'movement-first-purchase-cdo-lakrids-5l', stockItemId: 'stock-cdo-lakrids-5l', date: '2026-06-28', type: 'Received', quantity: 3, notes: 'First product purchase. Line cost 831,27 kr. excl. moms.' },
    { id: 'movement-first-purchase-cdo-saltet-karamel-5l', stockItemId: 'stock-cdo-saltet-karamel-5l', date: '2026-06-28', type: 'Received', quantity: 3, notes: 'First product purchase. Line cost 831,27 kr. excl. moms.' },
    { id: 'movement-first-purchase-frisko-regnbue-tutti-frutti-5l', stockItemId: 'stock-frisko-regnbue-tutti-frutti-5l', date: '2026-06-28', type: 'Received', quantity: 3, notes: 'First product purchase. Line cost 831,27 kr. excl. moms.' },
    { id: 'movement-first-purchase-cdo-hindbaersorbet-2-4l-x2', stockItemId: 'stock-cdo-hindbaersorbet-2-4l-x2', date: '2026-06-28', type: 'Received', quantity: 3, notes: 'First product purchase. Line cost 943,87 kr. excl. moms.' },
    { id: 'movement-first-purchase-cdo-mangosorbet-2-4l-x2', stockItemId: 'stock-cdo-mangosorbet-2-4l-x2', date: '2026-06-28', type: 'Received', quantity: 3, notes: 'First product purchase. Line cost 943,87 kr. excl. moms.' },
    { id: 'movement-first-purchase-cdo-mint-chokolade-5-5l', stockItemId: 'stock-cdo-mint-chokolade-5-5l', date: '2026-06-28', type: 'Received', quantity: 3, notes: 'First product purchase. Line cost 1.012,96 kr. excl. moms.' },
    { id: 'movement-first-purchase-softice-mix-5l', stockItemId: 'stock-softice-mix-5l', date: '2026-06-28', type: 'Received', quantity: 2, notes: 'First product purchase. Line cost 565,98 kr. excl. moms.' },
    { id: 'movement-more-purchases-cdo-pistacie-5l', stockItemId: 'stock-cdo-pistacie-5l', date: '2026-06-28', type: 'Received', quantity: 2, notes: 'Additional purchase receipt. Line cost 678,00 kr. incl. moms.' },
    { id: 'movement-more-purchases-idun-vaffel-3-kugler-240stk', stockItemId: 'stock-idun-vaffel-3-kugler-240stk', date: '2026-06-28', type: 'Received', quantity: 1, notes: 'Additional purchase receipt. Line cost 280,00 kr. incl. moms.' },
    { id: 'movement-more-purchases-idun-vaffel-2-kugler-390stk', stockItemId: 'stock-idun-vaffel-2-kugler-390stk', date: '2026-06-28', type: 'Received', quantity: 1, notes: 'Additional purchase receipt. Line cost 363,00 kr. incl. moms.' },
    { id: 'movement-more-purchases-debic-flodeskum-spray-700ml', stockItemId: 'stock-debic-flodeskum-spray-700ml', date: '2026-06-28', type: 'Received', quantity: 2, notes: 'Additional purchase receipt. Line cost 125,90 kr. incl. moms.' },
    { id: 'movement-softice-mix-purchase-2026-07-14', stockItemId: 'stock-softice-mix-5l', date: '2026-07-14', type: 'Received', quantity: 8, notes: 'Softice Mix invoice. Line cost 2.263,93 kr. excl. moms.' },
    { id: 'movement-ice-cream-restock-cdo-vanilla-5l-2026-07-14', stockItemId: 'stock-cdo-vanilla-5l', date: '2026-07-14', type: 'Received', quantity: 5, notes: 'Ice cream restock. Line cost 1.279,83 kr. excl. moms.' },
    { id: 'movement-ice-cream-restock-cdo-chocolate-5l-2026-07-14', stockItemId: 'stock-cdo-chocolate-5l', date: '2026-07-14', type: 'Received', quantity: 3, notes: 'Ice cream restock. Line cost 767,90 kr. excl. moms.' },
    { id: 'movement-ice-cream-restock-cdo-jordbaer-5l-2026-07-14', stockItemId: 'stock-cdo-jordbaer-5l', date: '2026-07-14', type: 'Received', quantity: 3, notes: 'Ice cream restock. Line cost 767,90 kr. excl. moms.' },
    { id: 'movement-ice-cream-restock-cdo-lakrids-5l-2026-07-14', stockItemId: 'stock-cdo-lakrids-5l', date: '2026-07-14', type: 'Received', quantity: 3, notes: 'Ice cream restock. Line cost 831,27 kr. excl. moms.' },
    { id: 'movement-ice-cream-restock-cdo-saltet-karamel-5l-2026-07-14', stockItemId: 'stock-cdo-saltet-karamel-5l', date: '2026-07-14', type: 'Received', quantity: 3, notes: 'Ice cream restock. Line cost 831,27 kr. excl. moms.' },
    { id: 'movement-ice-cream-restock-frisko-regnbue-tutti-frutti-5l-2026-07-14', stockItemId: 'stock-frisko-regnbue-tutti-frutti-5l', date: '2026-07-14', type: 'Received', quantity: 3, notes: 'Ice cream restock. Line cost 831,27 kr. excl. moms.' },
    { id: 'movement-ice-cream-restock-frisko-choco-cookie-5l-2026-07-14', stockItemId: 'stock-frisko-choco-cookie-5l', date: '2026-07-14', type: 'Received', quantity: 3, notes: 'Ice cream restock. Line cost 865,88 kr. excl. moms.' },
    { id: 'movement-ice-cream-restock-cdo-hindbaersorbet-2-4l-x2-2026-07-14', stockItemId: 'stock-cdo-hindbaersorbet-2-4l-x2', date: '2026-07-14', type: 'Received', quantity: 3, notes: 'Ice cream restock. Line cost 943,87 kr. excl. moms.' },
    { id: 'movement-ice-cream-restock-cdo-mangosorbet-2-4l-x2-2026-07-14', stockItemId: 'stock-cdo-mangosorbet-2-4l-x2', date: '2026-07-14', type: 'Received', quantity: 3, notes: 'Ice cream restock. Line cost 943,87 kr. excl. moms.' },
    { id: 'movement-ice-cream-restock-cdo-pistacie-5-5l-2026-07-14', stockItemId: 'stock-cdo-pistacie-5-5l', date: '2026-07-14', type: 'Received', quantity: 3, notes: 'Ice cream restock. Line cost 1.012,96 kr. excl. moms.' },
    { id: 'movement-ice-cream-restock-cdo-mint-chokolade-5-5l-2026-07-14', stockItemId: 'stock-cdo-mint-chokolade-5-5l', date: '2026-07-14', type: 'Received', quantity: 3, notes: 'Ice cream restock. Line cost 1.012,96 kr. excl. moms.' },
    { id: 'movement-ice-cream-restock-softice-mix-5l-2026-07-14', stockItemId: 'stock-softice-mix-5l', date: '2026-07-14', type: 'Received', quantity: 6, notes: 'Ice cream restock. Line cost 1.697,95 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-vanilla-5l-2026-07-17', stockItemId: 'stock-cdo-vanilla-5l', date: '2026-07-17', type: 'Received', quantity: 6, notes: 'Invoice 6356784764. Line cost 1.535,80 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-chocolate-5l-2026-07-17', stockItemId: 'stock-cdo-chocolate-5l', date: '2026-07-17', type: 'Received', quantity: 6, notes: 'Invoice 6356784764. Line cost 1.535,80 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-jordbaer-5l-2026-07-17', stockItemId: 'stock-cdo-jordbaer-5l', date: '2026-07-17', type: 'Received', quantity: 2, notes: 'Invoice 6356784764. Line cost 511,93 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-lakrids-5l-2026-07-17', stockItemId: 'stock-cdo-lakrids-5l', date: '2026-07-17', type: 'Received', quantity: 3, notes: 'Invoice 6356784764. Line cost 831,27 kr. excl. moms.' },
    { id: 'movement-unilever-restock-frisko-pistacie-5l-2026-07-17', stockItemId: 'stock-frisko-pistacie-5l', date: '2026-07-17', type: 'Received', quantity: 5, notes: 'Invoice 6356784764. Line cost 1.385,45 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-saltet-karamel-5l-2026-07-17', stockItemId: 'stock-cdo-saltet-karamel-5l', date: '2026-07-17', type: 'Received', quantity: 6, notes: 'Invoice 6356784764. Line cost 1.662,55 kr. excl. moms.' },
    { id: 'movement-unilever-restock-frisko-regnbue-tutti-frutti-5l-2026-07-17', stockItemId: 'stock-frisko-regnbue-tutti-frutti-5l', date: '2026-07-17', type: 'Received', quantity: 1, notes: 'Invoice 6356784764. Line cost 277,09 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-hindbaersorbet-2-4l-x2-2026-07-17', stockItemId: 'stock-cdo-hindbaersorbet-2-4l-x2', date: '2026-07-17', type: 'Received', quantity: 1, notes: 'Invoice 6356784764. Line cost 314,62 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-mangosorbet-2-4l-x2-2026-07-17', stockItemId: 'stock-cdo-mangosorbet-2-4l-x2', date: '2026-07-17', type: 'Received', quantity: 2, notes: 'Invoice 6356784764. Line cost 629,25 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-mint-chokolade-5-5l-2026-07-17', stockItemId: 'stock-cdo-mint-chokolade-5-5l', date: '2026-07-17', type: 'Received', quantity: 4, notes: 'Invoice 6356784764. Line cost 1.350,61 kr. excl. moms.' },
    { id: 'movement-unilever-restock-softice-mix-5l-2026-07-17', stockItemId: 'stock-softice-mix-5l', date: '2026-07-17', type: 'Received', quantity: 6, notes: 'Invoice 6356784764. Line cost 1.697,95 kr. excl. moms.' },
    { id: 'movement-unilever-restock-bj-cookie-dough-4-5l-x2-2026-07-17', stockItemId: 'stock-bj-cookie-dough-4-5l-x2', date: '2026-07-17', type: 'Received', quantity: 3, notes: 'Invoice 6356784764. Line cost 2.412,96 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-vanilla-5l-2026-08-12', stockItemId: 'stock-cdo-vanilla-5l', date: '2026-08-12', type: 'Received', quantity: 6, notes: 'Unilever restock. Line cost 1.535,80 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-chocolate-5l-2026-08-12', stockItemId: 'stock-cdo-chocolate-5l', date: '2026-08-12', type: 'Received', quantity: 2, notes: 'Unilever restock. Line cost 511,93 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-jordbaer-5l-2026-08-12', stockItemId: 'stock-cdo-jordbaer-5l', date: '2026-08-12', type: 'Received', quantity: 2, notes: 'Unilever restock. Line cost 511,93 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-lakrids-5l-2026-08-12', stockItemId: 'stock-cdo-lakrids-5l', date: '2026-08-12', type: 'Received', quantity: 2, notes: 'Unilever restock. Line cost 554,18 kr. excl. moms.' },
    { id: 'movement-unilever-restock-frisko-pistacie-5l-2026-08-12', stockItemId: 'stock-frisko-pistacie-5l', date: '2026-08-12', type: 'Received', quantity: 2, notes: 'Unilever restock. Line cost 554,18 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-saltet-karamel-5l-2026-08-12', stockItemId: 'stock-cdo-saltet-karamel-5l', date: '2026-08-12', type: 'Received', quantity: 1, notes: 'Unilever restock. Line cost 277,09 kr. excl. moms.' },
    { id: 'movement-unilever-restock-frisko-regnbue-tutti-frutti-5l-2026-08-12', stockItemId: 'stock-frisko-regnbue-tutti-frutti-5l', date: '2026-08-12', type: 'Received', quantity: 2, notes: 'Unilever restock. Line cost 554,18 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-hindbaersorbet-2-4l-x2-2026-08-12', stockItemId: 'stock-cdo-hindbaersorbet-2-4l-x2', date: '2026-08-12', type: 'Received', quantity: 4, notes: 'Unilever restock. Line cost 1.258,50 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-mangosorbet-2-4l-x2-2026-08-12', stockItemId: 'stock-cdo-mangosorbet-2-4l-x2', date: '2026-08-12', type: 'Received', quantity: 4, notes: 'Unilever restock. Line cost 1.258,50 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-mint-chokolade-5-5l-2026-08-12', stockItemId: 'stock-cdo-mint-chokolade-5-5l', date: '2026-08-12', type: 'Received', quantity: 1, notes: 'Unilever restock. Line cost 337,65 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-banana-chocolate-5-5l-2026-08-12', stockItemId: 'stock-cdo-banana-chocolate-5-5l', date: '2026-08-12', type: 'Received', quantity: 1, notes: 'Unilever restock. Line cost 337,65 kr. excl. moms.' },
    { id: 'movement-unilever-restock-cdo-raspberry-white-chocolate-5-5l-2026-08-12', stockItemId: 'stock-cdo-raspberry-white-chocolate-5-5l', date: '2026-08-12', type: 'Received', quantity: 1, notes: 'Unilever restock. Line cost 337,65 kr. excl. moms.' },
    { id: 'movement-unilever-restock-carte-dor-choc-hazelnut-5-5l-2026-08-12', stockItemId: 'stock-carte-dor-choc-hazelnut-5-5l', date: '2026-08-12', type: 'Received', quantity: 1, notes: 'Unilever restock. Line cost 337,65 kr. excl. moms.' },
    { id: 'movement-unilever-restock-softice-mix-5l-2026-08-12', stockItemId: 'stock-softice-mix-5l', date: '2026-08-12', type: 'Received', quantity: 10, notes: 'Unilever restock. Line cost 2.829,91 kr. excl. moms.' },
    { id: 'movement-unilever-restock-bj-cookie-dough-4-5l-x2-2026-08-12', stockItemId: 'stock-bj-cookie-dough-4-5l-x2', date: '2026-08-12', type: 'Received', quantity: 3, notes: 'Unilever restock. Line cost 2.412,96 kr. excl. moms.' },
  ],
  flavors: ['Vanilje', 'Chokolade', 'Lakrids', 'Citronsorbet', 'Oreo', 'Jordbær', 'Nougat'],
  settings: {
    vatRegistered: true,
    vatRate: 25,
    currency: 'DKK',
    salesPricesIncludeVat: true,
    productCostsIncludeVat: true,
    expensesIncludeVat: true,
    dailyRevenueGoal: 800,
    shopQuestGoalVersion: 1,
    gufBucketPriceExVat: 639.66,
    gufPortionsPerBucket: 100,
    businessName: 'IsVognen',
  },
}
