import type { AppData, ExpenseType, PaymentMethod, Product } from './types'

export const expenseTypes: ExpenseType[] = [
  'Ice cream purchase',
  'Waffles/cones',
  'Toppings/guf',
  'Staff wages',
  'Electricity',
  'Packaging',
  'Cleaning',
  'Rent',
  'Cash register system',
  'Card fees',
  'Other',
]

export const paymentMethods: PaymentMethod[] = ['Cash', 'Card', 'MobilePay', 'Bank', 'Other']

export const seedProducts: Product[] = [
  {
    id: 'alm-softice',
    name: 'Alm. Softice',
    category: 'Softice',
    portionSize: '1 portion',
    costPerUnit: 0,
    sellingPrice: 45,
    notes: '',
  },
  {
    id: 'lille-softice',
    name: 'Lille Softice',
    category: 'Softice',
    portionSize: '1 small portion',
    costPerUnit: 0,
    sellingPrice: 35,
    notes: '',
  },
  {
    id: '1-kugle',
    name: '1 Kugle',
    category: 'Kugleis',
    portionSize: '1 scoop',
    costPerUnit: 0,
    sellingPrice: 37,
    notes: '',
  },
  {
    id: '2-kugler',
    name: '2 Kugler',
    category: 'Kugleis',
    portionSize: '2 scoops',
    costPerUnit: 0,
    sellingPrice: 50,
    notes: '',
  },
  {
    id: '3-kugler',
    name: '3 Kugler',
    category: 'Kugleis',
    portionSize: '3 scoops',
    costPerUnit: 0,
    sellingPrice: 63,
    notes: '',
  },
  {
    id: 'drys',
    name: 'Drys',
    category: 'Topping',
    portionSize: '1 topping',
    costPerUnit: 0,
    sellingPrice: 7,
    notes: '',
  },
  {
    id: 'flodeskum',
    name: 'Flødeskum',
    category: 'Topping',
    portionSize: '1 topping',
    costPerUnit: 0,
    sellingPrice: 7,
    notes: '',
  },
  {
    id: 'syltetoj',
    name: 'Syltetøj',
    category: 'Topping',
    portionSize: '1 topping',
    costPerUnit: 0,
    sellingPrice: 7,
    notes: '',
  },
  {
    id: 'softice-topping',
    name: 'Softice Topping',
    category: 'Topping',
    portionSize: '1 topping',
    costPerUnit: 0,
    sellingPrice: 15,
    notes: '',
  },
  {
    id: 'guf',
    name: 'Guf',
    category: 'Add-on',
    portionSize: '1 portion',
    costPerUnit: 0,
    sellingPrice: 7,
    notes: 'Calculated from guf bucket settings unless manually overridden.',
    costSource: 'gufSetting',
  },
]

export const seedData: AppData = {
  products: seedProducts,
  dailyReports: [
    {
      id: 'report-2026-05-23',
      date: '2026-05-23',
      items: [
        { productId: 'drys', quantity: 3 },
        { productId: '1-kugle', quantity: 48 },
        { productId: '2-kugler', quantity: 44 },
        { productId: '3-kugler', quantity: 1 },
      ],
      notes: 'Example report from 23/05/2026.',
    },
  ],
  expenses: [],
  recurringExpenses: [
    {
      id: 'recurring-cash-register',
      type: 'Cash register system',
      description: 'Cash register system',
      amount: 0,
      paymentMethod: 'Card',
      dayOfMonth: 1,
      notes: 'Monthly payment. Enter the amount when you know it.',
      active: true,
    },
  ],
  stockItems: [
    {
      id: 'stock-guf',
      name: 'Guf portions',
      unit: 'portions',
      startingStock: 40,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 20,
      linkedProductId: 'guf',
      notes: 'Usage follows Guf sales.',
    },
    {
      id: 'stock-drys',
      name: 'Drys topping portions',
      unit: 'portions',
      startingStock: 5,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 10,
      linkedProductId: 'drys',
      notes: 'Seeded low to demonstrate reorder alerts.',
    },
    {
      id: 'stock-kugleis',
      name: 'Kugleis tubs',
      unit: 'tubs',
      startingStock: 7,
      addedStock: 0,
      manualUsedStock: 0,
      minimumStockLevel: 3,
      notes: 'Manual tracking first because scoop yield depends on tub size.',
    },
  ],
  stockMovements: [],
  flavors: ['Vanilje', 'Chokolade', 'Lakrids', 'Citronsorbet', 'Oreo', 'Jordbær', 'Nougat'],
  settings: {
    vatRegistered: true,
    vatRate: 25,
    currency: 'DKK',
    salesPricesIncludeVat: true,
    productCostsIncludeVat: true,
    expensesIncludeVat: true,
    dailyRevenueGoal: 800,
    shopQuestGoalVersion: 1,
    gufBucketPriceExVat: 639.66,
    gufPortionsPerBucket: 100,
    businessName: 'Isvognen / Ice Cream Booth',
  },
}
